version: "3"
services:

  cbaas-service-config:
    image: "registry.sbx.zone/cbaas/nodemon-dev-box"
    container_name: cbaas-service-config
    working_dir: /app
    volumes:
      - "./:/app"
    ports:
      - "9001:3001"
      - "9200:9229"
    environment:
      # common
      NODE_ENV: "development"
      PORT: 3001
      ALLOWED_KEYS: "[{\"key\": \"admin\", \"secret\": \"pass\"}]"
      # mongodb
      MONGO_URL: "mongodb://cbaas-mongodb:27017/cbaas"
      MONGO_USER: "admin"
      MONGO_PASSWORD: "pass"
      MONGO_COLLECTION: "products"
      # cloudant
#      DB_URL: "http://cbaas-cloudant"
#      DB_USER: "admin"
#      DB_PASSWORD: "pass"
#      DBA_USER: "admin"
#      DBA_PASSWORD: "pass"
#      DB_COLLECTION: "cbaas-product"
      CONFIG_PASSPHRASE: "5b3ff744-7607-4b40-bb04-414a8f4f5788"
      CONFIG_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: AES-256-CBC,7316CEF40D1F2F383617080D5F07E389\n\nVcBq2Wg4um4/ckn9LEJ3eK5igZRr4LT/q4dohkdMqnmQsD3Sx0rAI1EBcdg1cGaR\nkCcJULbd9VRibU4ifiFBFi7C7Mg3HIY2ObJsKKhx1HzmFpNNVf3Y6h7ddsuic2vv\nDUFgwnjf+v7b6GAPBp2Fntns71GKzCJ69idf8yvDIT7+smS+zhSvOODWUzHqAcjz\nZ1qzYH1uxMtXQAjy2mR2/D+mnTNEtsWSwzPpcjhTfl3bUeKXVUQEAjyoBJ+7HMwJ\nDB1oQYUoRBaldg+57THTkz05pnbglQQT17m8GUgbq8y9CKD0M8M3CKBvltcc/bsq\n3wsDJQorQdV4W0amsxwz0ZbN0J8zRzUDNMkQTUwLbt13F/PCYcMIkVUTDvWj6DWF\n4Uw0hJFNypOlD9AwELOkdf23IjifFPmejXOQoT/CatwkP32fNDfbsGVZ344gTQ4z\njg2yDwhxIHbuQAqMbRy+3iJ810VOcdrMEhPZiOZg8kLtOuccf7VBdYj4eAclQqoc\n3gP3ZYqqT2Z+A6mjhqhHIypD2WQHxh3w+NuDdc4lmjuZyHdK9CPSPcR6cdd3cmLY\nfSsCjyRXRvMbAmjVsFrrsLCs217HGXkIz9R/32IGWUM0f2aXIZk1j18EZzjTdYOg\ngisC5dhSIPsYLehFkbJe/3tHvNUkQNaKTk/fa3zRjpn4sZtaqAeG9PF6d3bHiN9W\n/6pODyLfvZfT0jvVbzjTkkCSSOlfHltyz1++BaTdNXgMDRvXyYPD1IXrsC8PTkRd\noD1w4D4EnxP43r2tk6CW6G0A9bIGggKvgjF5iVzKpp46RfWgjjigZsKykdrYjGUb\nGDLcwyU84UVv8FmHY3UUK5yjSIwD7rdHMTMlghmcastPE55VaIg/Ut3YxsV808iW\nk6o+KZLyeHcJUUuITZHkMNiZsS8tTTvxHE+98FvDXLKCDUlTFeFGWPq0yTKmeORC\nT61ac6TwKyO6ehF0e/gRcK+yB2akPqIVpqPI78sMdDf2AsyAGfywNu81TDjpZJ5o\n8RDPQzUG/kUZZGRZ+sv001GultCc6/ZlYq5JStrmOzzyDcrcALZP4rySCmVxuE7G\nnewPo20OtvNWWiF+nwR7/alpR5USH8SrSqMBLsZHhdv1X5IGbwRwAYpDFkX1gYR0\nEUbhvG4Flyw6I/BTblm1ze/rrKB4FW2gXRzhaQVKOt7pLmn4qxL//fvvaxpIAMCq\n564jgbbWxYr0iSnjMQ3HRD5x4S9JZfjJM6MvNO9Dy9MmwGjeUk4QTLhXvVWFGe+G\nOJVt0ap4aAQAwqNFUx5jnYgeYs/CaLIonsTL0F/BKCvgRRJ7lafYjpkLP5RjSxf5\nS38bcQnGioFjox0k4wnWFUDxjcjllDyQgzwSVcIwc3k37c5Y1rlqFRE1NdfqKjkl\nzfHUluoilShAbVaLd46IRXB501O9Zd4YBBiCGpf5WbsxUjtjTKL1/otepwoFfUqW\nHS7XLGNYAiAs+InzgDdn6j83jiaPQR9/icQ4HTktM8+M9q4xyDl9RsHPfdnFaJgY\nWDfdssnBm2dEImOW/TwXgScD7Ai3e60Mee0+mn0ARvOQqttlzI3tYmB3N7BJZAsX\n-----END RSA PRIVATE KEY-----"
      CONFIG_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyjXC2AqZyz6yQ3F/vmOw\nEUJo3yeNNVuuJincl5rK+tbwjaDcBSxdVVcJWGHe9a/JXrj10LuTptq16phJd1Ya\nbzCSqBivKGBDrJxLY5euoZ1ChvB8gIo1qH5zwy3obDpqQ1Av1PGVZgaaOK8tAFKI\nP+TBpb+iCgL9MOu3MBM0mYcArKGpJWEhdG8/h/heB8jgcMuAvdNehFPUM7Ec47E1\nlV8Wlgfel5NZ7b2sanOIZj+K6aPWlBdFaGBqhfBinaZLTHsez7WMSViTCVyVtPb6\njQPs5l8Ebv0eNue13gI/L2dOYHHEuejHr62T89CtMn9dHsKbzRacDv9bU4yMWrgR\n8wIDAQAB\n-----END PUBLIC KEY-----"
    # command: bash -c "sleep 15; node --inspect=0.0.0.0:9229 -r babel-register src/index.js"

  cbaas-cloudant:
    image: "registry.sbx.zone/ibmcom/cloudant-developer:latest"
    container_name: cbaas-cloudant
    ports:
      - "9000:80"
      - "5984:5984"
    expose:
      - "80"
      - "5984"
    privileged: true
    volumes:
      - ~/mnt:/srv
    
  cbaas-mongodb:
    image: "mongo"
    container_name: cbaas-mongodb
    ports:
    - "27017:27017"
    - "8888:8888"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "pass"
      MONGO_INITDB_DATABASE: admin
    volumes:
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  cbaas-mongo-ui:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: cbaas-mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "pass"

volumes:
  sc-caf-cloudant: